name: soundofmeme
description: "A FLutter Project fo Sound of meme Assignment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts:
  google_nav_bar:
  line_icons:
  http: ^1.2.2
  shared_preferences:
  fluttertoast:
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/